data:
  train_path: nas/datasets/combined_all.npz
  target_col: left_wall_dist
  batch_size: 128
  num_workers: 8
  val_split: 0.1
  pin_memory: true
  prefetch_factor: 2
training:
  max_epochs: 700
  lr: 5.0e-05
  weight_decay: 0.0001
  early_stopping_patience: 60
  lr_patience: 20
  lr_scheduler_factor: 0.5
  optimizer: adam
  scheduler: reduce_on_plateau
  auto_lr_find: false
  resume: false
  precision: '32'
  gradient_clip_val: 1.0
  profiler: null
model:
  arch_id: 8
  dynamic:
    in_channels: 1
    input_length: 1080
    activation: relu
    conv_layers:
    - out_channels: 80
      kernel_size: 3
      stride: 1
      padding: 0
      pool_size: 2
    - out_channels: 38
      kernel_size: 3
      stride: 1
      padding: 0
      pool_size: 4
    fc_layers:
    - 104
